# Generated by Django 4.0 on 2022-01-06 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardApps', '0002_post_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='email',
        ),
    ]
